// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_About_screen_init(void)
{
    ui_About = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_About, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_About, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_About, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AboutBackToMain = lv_imgbtn_create(ui_About);
    lv_imgbtn_set_src(ui_AboutBackToMain, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_back_released_png, NULL);
    lv_imgbtn_set_src(ui_AboutBackToMain, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_back_pressed_png, NULL);
    lv_obj_set_width(ui_AboutBackToMain, 32);
    lv_obj_set_height(ui_AboutBackToMain, 32);
    lv_obj_set_x(ui_AboutBackToMain, 2);
    lv_obj_set_y(ui_AboutBackToMain, 8);

    ui_ImageAboutMessage = lv_img_create(ui_About);
    lv_img_set_src(ui_ImageAboutMessage, &ui_img_about_message_png);
    lv_obj_set_width(ui_ImageAboutMessage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageAboutMessage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageAboutMessage, 27);
    lv_obj_set_y(ui_ImageAboutMessage, 18);
    lv_obj_set_align(ui_ImageAboutMessage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageAboutMessage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageAboutMessage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelAboutMessage = lv_label_create(ui_About);
    lv_obj_set_width(ui_LabelAboutMessage, 278);
    lv_obj_set_height(ui_LabelAboutMessage, 15);
    lv_obj_set_x(ui_LabelAboutMessage, 20);
    lv_obj_set_y(ui_LabelAboutMessage, 18);
    lv_obj_set_align(ui_LabelAboutMessage, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_LabelAboutMessage, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LabelAboutMessage, "Github: CaddonThaw b站: 会打狙的船长");
    lv_obj_set_style_text_color(ui_LabelAboutMessage, lv_color_hex(0x00A7FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAboutMessage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAboutMessage, &ui_font_AlimamaShuHeiTiFont16Bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageAbout1 = lv_img_create(ui_About);
    lv_img_set_src(ui_ImageAbout1, &ui_img_about_luoxiaohei1_png);
    lv_obj_set_width(ui_ImageAbout1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageAbout1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageAbout1, -130);
    lv_obj_set_y(ui_ImageAbout1, -43);
    lv_obj_set_align(ui_ImageAbout1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageAbout1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageAbout1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageAbout2 = lv_img_create(ui_About);
    lv_img_set_src(ui_ImageAbout2, &ui_img_about_luoxiaohei3_png);
    lv_obj_set_width(ui_ImageAbout2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageAbout2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageAbout2, -130);
    lv_obj_set_y(ui_ImageAbout2, 7);
    lv_obj_set_align(ui_ImageAbout2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageAbout2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageAbout2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageAbout3 = lv_img_create(ui_About);
    lv_img_set_src(ui_ImageAbout3, &ui_img_about_luoxiaohei2_png);
    lv_obj_set_width(ui_ImageAbout3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageAbout3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageAbout3, -130);
    lv_obj_set_y(ui_ImageAbout3, 57);
    lv_obj_set_align(ui_ImageAbout3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageAbout3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageAbout3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_AboutBackToMain, ui_event_AboutBackToMain, LV_EVENT_ALL, NULL);

}
