// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Cal_screen_init(void)
{
    ui_Cal = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Cal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Cal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Cal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalBackToMain = lv_imgbtn_create(ui_Cal);
    lv_imgbtn_set_src(ui_CalBackToMain, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_back_released_png, NULL);
    lv_imgbtn_set_src(ui_CalBackToMain, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_back_pressed_png, NULL);
    lv_obj_set_width(ui_CalBackToMain, 32);
    lv_obj_set_height(ui_CalBackToMain, 32);
    lv_obj_set_x(ui_CalBackToMain, 2);
    lv_obj_set_y(ui_CalBackToMain, 8);

    ui_Calendar = lv_calendar_create(ui_Cal);
    lv_calendar_set_today_date(ui_Calendar, 2025, 11, 30);
    lv_calendar_set_showed_date(ui_Calendar, 2025, 11);
    lv_obj_t * ui_Calendar_header = lv_calendar_header_arrow_create(ui_Calendar);
    lv_obj_set_width(ui_Calendar, 270);
    lv_obj_set_height(ui_Calendar, 193);
    lv_obj_set_x(ui_Calendar, 0);
    lv_obj_set_y(ui_Calendar, 12);
    lv_obj_set_align(ui_Calendar, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_CalBackToMain, ui_event_CalBackToMain, LV_EVENT_ALL, NULL);

}
