// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Game_screen_init(void)
{
    ui_Game = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Game, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Game, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Game, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GameBackToMain = lv_imgbtn_create(ui_Game);
    lv_imgbtn_set_src(ui_GameBackToMain, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_back_released_png, NULL);
    lv_imgbtn_set_src(ui_GameBackToMain, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_back_pressed_png, NULL);
    lv_obj_set_width(ui_GameBackToMain, 32);
    lv_obj_set_height(ui_GameBackToMain, 32);
    lv_obj_set_x(ui_GameBackToMain, 2);
    lv_obj_set_y(ui_GameBackToMain, 8);

    ui_ButtonGame2048 = lv_btn_create(ui_Game);
    lv_obj_set_width(ui_ButtonGame2048, 100);
    lv_obj_set_height(ui_ButtonGame2048, 50);
    lv_obj_set_x(ui_ButtonGame2048, -75);
    lv_obj_set_y(ui_ButtonGame2048, -50);
    lv_obj_set_align(ui_ButtonGame2048, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ButtonGame2048, lv_color_hex(0xFF8700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonGame2048, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelGame2048 = lv_label_create(ui_ButtonGame2048);
    lv_obj_set_width(ui_LabelGame2048, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelGame2048, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelGame2048, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelGame2048, "2048");
    lv_obj_set_style_text_font(ui_LabelGame2048, &ui_font_AlimamaShuHeiTiFont16Bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonGameYang = lv_btn_create(ui_Game);
    lv_obj_set_width(ui_ButtonGameYang, 100);
    lv_obj_set_height(ui_ButtonGameYang, 50);
    lv_obj_set_x(ui_ButtonGameYang, 75);
    lv_obj_set_y(ui_ButtonGameYang, -50);
    lv_obj_set_align(ui_ButtonGameYang, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ButtonGameYang, lv_color_hex(0x00BCFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonGameYang, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelGameYang = lv_label_create(ui_ButtonGameYang);
    lv_obj_set_width(ui_LabelGameYang, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelGameYang, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelGameYang, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelGameYang, "羊了个羊");
    lv_obj_set_style_text_font(ui_LabelGameYang, &ui_font_AlimamaShuHeiTiFont16Bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonGameXiao = lv_btn_create(ui_Game);
    lv_obj_set_width(ui_ButtonGameXiao, 100);
    lv_obj_set_height(ui_ButtonGameXiao, 50);
    lv_obj_set_x(ui_ButtonGameXiao, -75);
    lv_obj_set_y(ui_ButtonGameXiao, 50);
    lv_obj_set_align(ui_ButtonGameXiao, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ButtonGameXiao, lv_color_hex(0xFB00F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonGameXiao, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelGameXiao = lv_label_create(ui_ButtonGameXiao);
    lv_obj_set_width(ui_LabelGameXiao, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelGameXiao, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelGameXiao, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelGameXiao, "消消乐");
    lv_obj_set_style_text_font(ui_LabelGameXiao, &ui_font_AlimamaShuHeiTiFont16Bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonGamePvz = lv_btn_create(ui_Game);
    lv_obj_set_width(ui_ButtonGamePvz, 100);
    lv_obj_set_height(ui_ButtonGamePvz, 50);
    lv_obj_set_x(ui_ButtonGamePvz, 75);
    lv_obj_set_y(ui_ButtonGamePvz, 50);
    lv_obj_set_align(ui_ButtonGamePvz, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ButtonGamePvz, lv_color_hex(0x791414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonGamePvz, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelGamePvz = lv_label_create(ui_ButtonGamePvz);
    lv_obj_set_width(ui_LabelGamePvz, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelGamePvz, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelGamePvz, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelGamePvz, "植物大战僵尸");
    lv_obj_set_style_text_font(ui_LabelGamePvz, &ui_font_AlimamaShuHeiTiFont16Bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_GameBackToMain, ui_event_GameBackToMain, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonGame2048, ui_event_ButtonGame2048, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonGameYang, ui_event_ButtonGameYang, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonGameXiao, ui_event_ButtonGameXiao, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonGamePvz, ui_event_ButtonGamePvz, LV_EVENT_ALL, NULL);

}
