// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_GPT_screen_init(void)
{
    ui_GPT = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_GPT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GPT, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GPT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_GPT, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GPT, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_GPTBackToMain = lv_imgbtn_create(ui_GPT);
    lv_imgbtn_set_src(ui_GPTBackToMain, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_back_released_png, NULL);
    lv_imgbtn_set_src(ui_GPTBackToMain, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_back_pressed_png, NULL);
    lv_obj_set_width(ui_GPTBackToMain, 32);
    lv_obj_set_height(ui_GPTBackToMain, 32);
    lv_obj_set_x(ui_GPTBackToMain, 2);
    lv_obj_set_y(ui_GPTBackToMain, 8);

    ui_TextAreaXiaozhiQuestion = lv_textarea_create(ui_GPT);
    lv_obj_set_width(ui_TextAreaXiaozhiQuestion, 200);
    lv_obj_set_height(ui_TextAreaXiaozhiQuestion, 60);
    lv_obj_set_x(ui_TextAreaXiaozhiQuestion, 60);
    lv_obj_set_y(ui_TextAreaXiaozhiQuestion, 30);
    lv_textarea_set_text(ui_TextAreaXiaozhiQuestion, "请连接WiFi后使用小智功能哦~");
    lv_obj_set_style_text_color(ui_TextAreaXiaozhiQuestion, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextAreaXiaozhiQuestion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaXiaozhiQuestion, &ui_font_AlimamaShuHeiTiFont16Bpp4,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextAreaXiaozhiQuestion, lv_color_hex(0x00FFC4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextAreaXiaozhiQuestion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_ButtonXiaoZhiQuestion = lv_btn_create(ui_GPT);
    lv_obj_set_width(ui_ButtonXiaoZhiQuestion, 40);
    lv_obj_set_height(ui_ButtonXiaoZhiQuestion, 40);
    lv_obj_set_x(ui_ButtonXiaoZhiQuestion, -5);
    lv_obj_set_y(ui_ButtonXiaoZhiQuestion, 40);
    lv_obj_set_align(ui_ButtonXiaoZhiQuestion, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_radius(ui_ButtonXiaoZhiQuestion, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonXiaoZhiQuestion, lv_color_hex(0x18FFCA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonXiaoZhiQuestion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelXiaoZhiQuestion = lv_label_create(ui_ButtonXiaoZhiQuestion);
    lv_obj_set_width(ui_LabelXiaoZhiQuestion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelXiaoZhiQuestion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelXiaoZhiQuestion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelXiaoZhiQuestion, "^ ^");
    lv_obj_set_style_text_color(ui_LabelXiaoZhiQuestion, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelXiaoZhiQuestion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaXiaoZhiAnswer = lv_textarea_create(ui_GPT);
    lv_obj_set_width(ui_TextAreaXiaoZhiAnswer, 256);
    lv_obj_set_height(ui_TextAreaXiaoZhiAnswer, 131);
    lv_obj_set_x(ui_TextAreaXiaoZhiAnswer, 60);
    lv_obj_set_y(ui_TextAreaXiaoZhiAnswer, 100);
    lv_textarea_set_text(ui_TextAreaXiaoZhiAnswer, "请连接WiFi后使用小智功能哦~");
    lv_obj_set_style_text_opa(ui_TextAreaXiaoZhiAnswer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaXiaoZhiAnswer, &ui_font_AlimamaShuHeiTiFont16Bpp4,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextAreaXiaoZhiAnswer, lv_color_hex(0xFF00AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextAreaXiaoZhiAnswer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_ButtonXiaoZhiAnswer = lv_btn_create(ui_GPT);
    lv_obj_set_width(ui_ButtonXiaoZhiAnswer, 40);
    lv_obj_set_height(ui_ButtonXiaoZhiAnswer, 40);
    lv_obj_set_x(ui_ButtonXiaoZhiAnswer, 5);
    lv_obj_set_y(ui_ButtonXiaoZhiAnswer, 100);
    lv_obj_set_style_radius(ui_ButtonXiaoZhiAnswer, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonXiaoZhiAnswer, lv_color_hex(0xFF2BBA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonXiaoZhiAnswer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelXiaoZhiAnswer = lv_label_create(ui_ButtonXiaoZhiAnswer);
    lv_obj_set_width(ui_LabelXiaoZhiAnswer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelXiaoZhiAnswer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelXiaoZhiAnswer, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelXiaoZhiAnswer, "^ ^");
    lv_obj_set_style_text_color(ui_LabelXiaoZhiAnswer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelXiaoZhiAnswer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchXiaoZhiSpeak = lv_switch_create(ui_GPT);
    lv_obj_set_width(ui_SwitchXiaoZhiSpeak, 36);
    lv_obj_set_height(ui_SwitchXiaoZhiSpeak, 36);
    lv_obj_set_x(ui_SwitchXiaoZhiSpeak, 15);
    lv_obj_set_y(ui_SwitchXiaoZhiSpeak, 45);
    lv_obj_set_style_radius(ui_SwitchXiaoZhiSpeak, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SwitchXiaoZhiSpeak, lv_color_hex(0x4C484C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchXiaoZhiSpeak, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SwitchXiaoZhiSpeak, 30, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SwitchXiaoZhiSpeak, lv_color_hex(0x9DA5AB), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchXiaoZhiSpeak, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_add_state(ui_SwitchXiaoZhiSpeak, LV_STATE_DISABLED);

    ui_LabelXiaoZhiSpeak = lv_label_create(ui_SwitchXiaoZhiSpeak);
    lv_obj_set_width(ui_LabelXiaoZhiSpeak, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelXiaoZhiSpeak, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelXiaoZhiSpeak, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelXiaoZhiSpeak, "OFF");
    lv_obj_set_style_text_font(ui_LabelXiaoZhiSpeak, &ui_font_AlimamaShuHeiTiFont16Bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_GPTBackToMain, ui_event_GPTBackToMain, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchXiaoZhiSpeak, ui_event_SwitchXiaoZhiSpeak, LV_EVENT_ALL, NULL);

}
