// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_GameSon_screen_init(void)
{
    ui_GameSon = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_GameSon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GameSonBackToGame = lv_imgbtn_create(ui_GameSon);
    lv_imgbtn_set_src(ui_GameSonBackToGame, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_back_released_png, NULL);
    lv_imgbtn_set_src(ui_GameSonBackToGame, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_back_pressed_png, NULL);
    lv_obj_set_width(ui_GameSonBackToGame, 32);
    lv_obj_set_height(ui_GameSonBackToGame, 32);
    lv_obj_set_x(ui_GameSonBackToGame, 2);
    lv_obj_set_y(ui_GameSonBackToGame, 8);

    lv_obj_add_event_cb(ui_GameSonBackToGame, ui_event_GameSonBackToGame, LV_EVENT_ALL, NULL);

}
