// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_add_flag(ui_Main, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Main, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabViewApp = lv_tabview_create(ui_Main, LV_DIR_TOP, 0);
    lv_obj_set_width(ui_TabViewApp, 271);
    lv_obj_set_height(ui_TabViewApp, 79);
    lv_obj_set_x(ui_TabViewApp, 0);
    lv_obj_set_y(ui_TabViewApp, 42);
    lv_obj_set_align(ui_TabViewApp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabViewApp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


    ui_TabPageApp = lv_tabview_add_tab(ui_TabViewApp, "App");
    lv_obj_set_style_bg_color(ui_TabPageApp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabPageApp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSet = lv_obj_create(ui_TabPageApp);
    lv_obj_set_width(ui_PanelSet, 48);
    lv_obj_set_height(ui_PanelSet, 67);
    lv_obj_set_x(ui_PanelSet, -105);
    lv_obj_set_y(ui_PanelSet, 0);
    lv_obj_set_align(ui_PanelSet, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_PanelSet, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelSet, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ToSet = lv_imgbtn_create(ui_PanelSet);
    lv_imgbtn_set_src(ui_ToSet, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_set_released_png, NULL);
    lv_imgbtn_set_src(ui_ToSet, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_set_pressed_png, NULL);
    lv_obj_set_width(ui_ToSet, 48);
    lv_obj_set_height(ui_ToSet, 48);
    lv_obj_set_x(ui_ToSet, -2);
    lv_obj_set_y(ui_ToSet, -8);
    lv_obj_set_align(ui_ToSet, LV_ALIGN_CENTER);

    ui_LabelSet = lv_label_create(ui_PanelSet);
    lv_obj_set_width(ui_LabelSet, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSet, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSet, -2);
    lv_obj_set_y(ui_LabelSet, 25);
    lv_obj_set_align(ui_LabelSet, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSet, "设置");
    lv_obj_set_style_text_color(ui_LabelSet, lv_color_hex(0x2D302D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSet, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSet, &ui_font_AlimamaShuHeiTiFont16Bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSerial = lv_obj_create(ui_TabPageApp);
    lv_obj_set_width(ui_PanelSerial, 48);
    lv_obj_set_height(ui_PanelSerial, 68);
    lv_obj_set_x(ui_PanelSerial, -40);
    lv_obj_set_y(ui_PanelSerial, 0);
    lv_obj_set_align(ui_PanelSerial, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSerial, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_PanelSerial, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelSerial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ToSerial = lv_imgbtn_create(ui_PanelSerial);
    lv_imgbtn_set_src(ui_ToSerial, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_serial_released_png, NULL);
    lv_imgbtn_set_src(ui_ToSerial, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_serial_pressed_png, NULL);
    lv_obj_set_width(ui_ToSerial, 48);
    lv_obj_set_height(ui_ToSerial, 48);
    lv_obj_set_x(ui_ToSerial, -2);
    lv_obj_set_y(ui_ToSerial, -8);
    lv_obj_set_align(ui_ToSerial, LV_ALIGN_CENTER);

    ui_LabelSerial = lv_label_create(ui_PanelSerial);
    lv_obj_set_width(ui_LabelSerial, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSerial, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSerial, -2);
    lv_obj_set_y(ui_LabelSerial, 25);
    lv_obj_set_align(ui_LabelSerial, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSerial, "串口");
    lv_obj_set_style_text_color(ui_LabelSerial, lv_color_hex(0x1095DE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSerial, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSerial, &ui_font_AlimamaShuHeiTiFont16Bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelWeather = lv_obj_create(ui_TabPageApp);
    lv_obj_set_width(ui_PanelWeather, 56);
    lv_obj_set_height(ui_PanelWeather, 71);
    lv_obj_set_x(ui_PanelWeather, 25);
    lv_obj_set_y(ui_PanelWeather, 0);
    lv_obj_set_align(ui_PanelWeather, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelWeather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_PanelWeather, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelWeather, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ToWeather = lv_imgbtn_create(ui_PanelWeather);
    lv_imgbtn_set_src(ui_ToWeather, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_weather_released_png, NULL);
    lv_imgbtn_set_src(ui_ToWeather, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_weather_pressed_png, NULL);
    lv_obj_set_width(ui_ToWeather, 48);
    lv_obj_set_height(ui_ToWeather, 48);
    lv_obj_set_x(ui_ToWeather, -2);
    lv_obj_set_y(ui_ToWeather, -8);
    lv_obj_set_align(ui_ToWeather, LV_ALIGN_CENTER);

    ui_LabelWeather = lv_label_create(ui_PanelWeather);
    lv_obj_set_width(ui_LabelWeather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWeather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWeather, -2);
    lv_obj_set_y(ui_LabelWeather, 25);
    lv_obj_set_align(ui_LabelWeather, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWeather, "天气");
    lv_obj_set_style_text_color(ui_LabelWeather, lv_color_hex(0xEE9540), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWeather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWeather, &ui_font_AlimamaShuHeiTiFont16Bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelMusic = lv_obj_create(ui_TabPageApp);
    lv_obj_set_width(ui_PanelMusic, 54);
    lv_obj_set_height(ui_PanelMusic, 70);
    lv_obj_set_x(ui_PanelMusic, 90);
    lv_obj_set_y(ui_PanelMusic, 0);
    lv_obj_set_align(ui_PanelMusic, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelMusic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_PanelMusic, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelMusic, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ToMusic = lv_imgbtn_create(ui_PanelMusic);
    lv_imgbtn_set_src(ui_ToMusic, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_music_released_png, NULL);
    lv_imgbtn_set_src(ui_ToMusic, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_music_pressed_png, NULL);
    lv_obj_set_width(ui_ToMusic, 48);
    lv_obj_set_height(ui_ToMusic, 48);
    lv_obj_set_x(ui_ToMusic, -2);
    lv_obj_set_y(ui_ToMusic, -8);
    lv_obj_set_align(ui_ToMusic, LV_ALIGN_CENTER);

    ui_LabelMusic = lv_label_create(ui_PanelMusic);
    lv_obj_set_width(ui_LabelMusic, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMusic, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMusic, -2);
    lv_obj_set_y(ui_LabelMusic, 25);
    lv_obj_set_align(ui_LabelMusic, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMusic, "音乐");
    lv_obj_set_style_text_color(ui_LabelMusic, lv_color_hex(0xDE1C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMusic, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMusic, &ui_font_AlimamaShuHeiTiFont16Bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelGPT = lv_obj_create(ui_TabPageApp);
    lv_obj_set_width(ui_PanelGPT, 56);
    lv_obj_set_height(ui_PanelGPT, 71);
    lv_obj_set_x(ui_PanelGPT, -105);
    lv_obj_set_y(ui_PanelGPT, 80);
    lv_obj_set_align(ui_PanelGPT, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelGPT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_PanelGPT, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelGPT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ToGPT = lv_imgbtn_create(ui_PanelGPT);
    lv_imgbtn_set_src(ui_ToGPT, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_gpt_released_png, NULL);
    lv_imgbtn_set_src(ui_ToGPT, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_gpt_pressed_png, NULL);
    lv_obj_set_width(ui_ToGPT, 48);
    lv_obj_set_height(ui_ToGPT, 48);
    lv_obj_set_x(ui_ToGPT, -2);
    lv_obj_set_y(ui_ToGPT, -8);
    lv_obj_set_align(ui_ToGPT, LV_ALIGN_CENTER);

    ui_LabelGPT = lv_label_create(ui_PanelGPT);
    lv_obj_set_width(ui_LabelGPT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelGPT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelGPT, -2);
    lv_obj_set_y(ui_LabelGPT, 25);
    lv_obj_set_align(ui_LabelGPT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelGPT, "小智");
    lv_obj_set_style_text_color(ui_LabelGPT, lv_color_hex(0x34BA9C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelGPT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelGPT, &ui_font_AlimamaShuHeiTiFont16Bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelGame = lv_obj_create(ui_TabPageApp);
    lv_obj_set_width(ui_PanelGame, 54);
    lv_obj_set_height(ui_PanelGame, 80);
    lv_obj_set_x(ui_PanelGame, -40);
    lv_obj_set_y(ui_PanelGame, 80);
    lv_obj_set_align(ui_PanelGame, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelGame, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_PanelGame, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelGame, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ToGame = lv_imgbtn_create(ui_PanelGame);
    lv_imgbtn_set_src(ui_ToGame, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_game_released_png, NULL);
    lv_imgbtn_set_src(ui_ToGame, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_game_pressed_png, NULL);
    lv_obj_set_width(ui_ToGame, 48);
    lv_obj_set_height(ui_ToGame, 48);
    lv_obj_set_x(ui_ToGame, -2);
    lv_obj_set_y(ui_ToGame, -13);
    lv_obj_set_align(ui_ToGame, LV_ALIGN_CENTER);

    ui_LabelGame = lv_label_create(ui_PanelGame);
    lv_obj_set_width(ui_LabelGame, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelGame, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelGame, -2);
    lv_obj_set_y(ui_LabelGame, 25);
    lv_obj_set_align(ui_LabelGame, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelGame, "游戏");
    lv_obj_set_style_text_color(ui_LabelGame, lv_color_hex(0xAF54FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelGame, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelGame, &ui_font_AlimamaShuHeiTiFont16Bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCal = lv_obj_create(ui_TabPageApp);
    lv_obj_set_width(ui_PanelCal, 56);
    lv_obj_set_height(ui_PanelCal, 71);
    lv_obj_set_x(ui_PanelCal, 25);
    lv_obj_set_y(ui_PanelCal, 80);
    lv_obj_set_align(ui_PanelCal, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelCal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_PanelCal, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelCal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ToCal = lv_imgbtn_create(ui_PanelCal);
    lv_imgbtn_set_src(ui_ToCal, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_cal_released_png, NULL);
    lv_imgbtn_set_src(ui_ToCal, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_cal_released_png, NULL);
    lv_obj_set_width(ui_ToCal, 48);
    lv_obj_set_height(ui_ToCal, 48);
    lv_obj_set_x(ui_ToCal, -2);
    lv_obj_set_y(ui_ToCal, -8);
    lv_obj_set_align(ui_ToCal, LV_ALIGN_CENTER);

    ui_LabelCal = lv_label_create(ui_PanelCal);
    lv_obj_set_width(ui_LabelCal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCal, -2);
    lv_obj_set_y(ui_LabelCal, 25);
    lv_obj_set_align(ui_LabelCal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCal, "日历");
    lv_obj_set_style_text_color(ui_LabelCal, lv_color_hex(0xFF5041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCal, &ui_font_AlimamaShuHeiTiFont16Bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelAbout = lv_obj_create(ui_TabPageApp);
    lv_obj_set_width(ui_PanelAbout, 60);
    lv_obj_set_height(ui_PanelAbout, 71);
    lv_obj_set_x(ui_PanelAbout, 90);
    lv_obj_set_y(ui_PanelAbout, 80);
    lv_obj_set_align(ui_PanelAbout, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelAbout, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_PanelAbout, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelAbout, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ToAbout = lv_imgbtn_create(ui_PanelAbout);
    lv_imgbtn_set_src(ui_ToAbout, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_about_released_png, NULL);
    lv_imgbtn_set_src(ui_ToAbout, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_about_released_png, NULL);
    lv_obj_set_width(ui_ToAbout, 48);
    lv_obj_set_height(ui_ToAbout, 48);
    lv_obj_set_x(ui_ToAbout, -2);
    lv_obj_set_y(ui_ToAbout, -8);
    lv_obj_set_align(ui_ToAbout, LV_ALIGN_CENTER);

    ui_LabelAbout = lv_label_create(ui_PanelAbout);
    lv_obj_set_width(ui_LabelAbout, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAbout, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAbout, -2);
    lv_obj_set_y(ui_LabelAbout, 25);
    lv_obj_set_align(ui_LabelAbout, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAbout, "关于");
    lv_obj_set_style_text_color(ui_LabelAbout, lv_color_hex(0xB48141), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAbout, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAbout, &ui_font_AlimamaShuHeiTiFont16Bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTime = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_PanelTime, 271);
    lv_obj_set_height(ui_PanelTime, 69);
    lv_obj_set_x(ui_PanelTime, 0);
    lv_obj_set_y(ui_PanelTime, -42);
    lv_obj_set_align(ui_PanelTime, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_PanelTime, lv_color_hex(0x00ABFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTime1 = lv_label_create(ui_PanelTime);
    lv_obj_set_width(ui_LabelTime1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTime1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTime1, -4);
    lv_obj_set_y(ui_LabelTime1, -10);
    lv_obj_set_align(ui_LabelTime1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTime1, "00:00:00");
    lv_obj_set_style_text_color(ui_LabelTime1, lv_color_hex(0xC800FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTime1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTime1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTime2 = lv_label_create(ui_PanelTime);
    lv_obj_set_width(ui_LabelTime2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTime2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTime2, -42);
    lv_obj_set_y(ui_LabelTime2, 21);
    lv_obj_set_align(ui_LabelTime2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTime2, "2025/11/29 星期六");
    lv_obj_set_style_text_color(ui_LabelTime2, lv_color_hex(0xC800FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTime2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTime2, &ui_font_AlimamaShuHeiTiFont16Bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelInit = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_PanelInit, 320);
    lv_obj_set_height(ui_PanelInit, 37);
    lv_obj_set_x(ui_PanelInit, 0);
    lv_obj_set_y(ui_PanelInit, -102);
    lv_obj_set_align(ui_PanelInit, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelInit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelInit, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelInit, lv_color_hex(0x005EFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelInit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelInit = lv_label_create(ui_PanelInit);
    lv_obj_set_width(ui_LabelInit, 259);
    lv_obj_set_height(ui_LabelInit, 20);
    lv_obj_set_x(ui_LabelInit, -26);
    lv_obj_set_y(ui_LabelInit, 1);
    lv_obj_set_align(ui_LabelInit, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabelInit, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LabelInit,
                      "欢迎来到广东工业大学 Welcome to University of Science and Technology of China");
    lv_obj_set_style_text_color(ui_LabelInit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelInit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelInit, &ui_font_AlimamaShuHeiTiFont16Bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchWiFi = lv_switch_create(ui_PanelInit);
    lv_obj_set_width(ui_SwitchWiFi, 32);
    lv_obj_set_height(ui_SwitchWiFi, 32);
    lv_obj_set_align(ui_SwitchWiFi, LV_ALIGN_RIGHT_MID);
    lv_obj_add_state(ui_SwitchWiFi, LV_STATE_DISABLED);       /// States
    lv_obj_set_style_bg_color(ui_SwitchWiFi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchWiFi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SwitchWiFi, &ui_img_wifi_pressed_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SwitchWiFi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_SwitchWiFi, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_src(ui_SwitchWiFi, &ui_img_wifi_released_png, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_SwitchWiFi, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_SwitchWiFi, 0, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_SwitchWiFi, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchWiFi, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SwitchWiFi, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_SwitchWiFi, 0, LV_PART_KNOB | LV_STATE_CHECKED);

    lv_obj_add_event_cb(ui_ToSet, ui_event_ToSet, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ToSerial, ui_event_ToSerial, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ToWeather, ui_event_ToWeather, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ToMusic, ui_event_ToMusic, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ToGPT, ui_event_ToGPT, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ToGame, ui_event_ToGame, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ToCal, ui_event_ToCal, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ToAbout, ui_event_ToAbout, LV_EVENT_ALL, NULL);

}
