// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Set_screen_init(void)
{
    ui_Set = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Set, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Set, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Set, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Set, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Set, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_SetBackToMain = lv_imgbtn_create(ui_Set);
    lv_imgbtn_set_src(ui_SetBackToMain, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_back_released_png, NULL);
    lv_imgbtn_set_src(ui_SetBackToMain, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_back_pressed_png, NULL);
    lv_obj_set_width(ui_SetBackToMain, 32);
    lv_obj_set_height(ui_SetBackToMain, 32);
    lv_obj_set_x(ui_SetBackToMain, 2);
    lv_obj_set_y(ui_SetBackToMain, 8);

    ui_PanelLight = lv_obj_create(ui_Set);
    lv_obj_set_width(ui_PanelLight, 248);
    lv_obj_set_height(ui_PanelLight, 48);
    lv_obj_set_x(ui_PanelLight, -3);
    lv_obj_set_y(ui_PanelLight, -56);
    lv_obj_set_align(ui_PanelLight, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelLight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelLight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelLight, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelLight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderLight = lv_slider_create(ui_PanelLight);
    lv_slider_set_value(ui_SliderLight, 100, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderLight) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderLight, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderLight, 148);
    lv_obj_set_height(ui_SliderLight, 15);
    lv_obj_set_x(ui_SliderLight, 31);
    lv_obj_set_y(ui_SliderLight, 1);
    lv_obj_set_style_bg_color(ui_SliderLight, lv_color_hex(0x8A8A8A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderLight, lv_color_hex(0xD599FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderLight, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderLight, lv_color_hex(0x8BF6FF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderLight, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelLightValue = lv_label_create(ui_PanelLight);
    lv_obj_set_width(ui_LabelLightValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLightValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLightValue, 104);
    lv_obj_set_y(ui_LabelLightValue, -1);
    lv_obj_set_align(ui_LabelLightValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLightValue, "100%");

    ui_LabelLight = lv_label_create(ui_PanelLight);
    lv_obj_set_width(ui_LabelLight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLight, -107);
    lv_obj_set_y(ui_LabelLight, -1);
    lv_obj_set_align(ui_LabelLight, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLight, "亮度");
    lv_obj_set_style_text_color(ui_LabelLight, lv_color_hex(0xFF8F00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelLight, &ui_font_AlimamaShuHeiTiFont16Bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelWiFi = lv_obj_create(ui_Set);
    lv_obj_set_width(ui_PanelWiFi, 306);
    lv_obj_set_height(ui_PanelWiFi, 154);
    lv_obj_set_x(ui_PanelWiFi, -1);
    lv_obj_set_y(ui_PanelWiFi, 36);
    lv_obj_set_align(ui_PanelWiFi, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelWiFi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelWiFi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelWiFi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelWiFi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelWiFi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollerWiFi = lv_roller_create(ui_PanelWiFi);
    lv_roller_set_options(ui_RollerWiFi, "正在扫描附近WiFi...", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_RollerWiFi, 224);
    lv_obj_set_height(ui_RollerWiFi, 114);
    lv_obj_set_x(ui_RollerWiFi, -4);
    lv_obj_set_y(ui_RollerWiFi, 15);
    lv_obj_set_align(ui_RollerWiFi, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_RollerWiFi, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerWiFi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RollerWiFi, &ui_font_AlimamaShuHeiTiFont16Bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RollerWiFi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerWiFi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RollerWiFi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RollerWiFi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_RollerWiFi, lv_color_hex(0x4F4F4F), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerWiFi, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_LabelWiFi = lv_label_create(ui_PanelWiFi);
    lv_obj_set_width(ui_LabelWiFi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWiFi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWiFi, -107);
    lv_obj_set_y(ui_LabelWiFi, -53);
    lv_obj_set_align(ui_LabelWiFi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWiFi, "WiFi");
    lv_obj_set_style_text_color(ui_LabelWiFi, lv_color_hex(0xFF8F00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWiFi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWiFi, &ui_font_AlimamaShuHeiTiFont16Bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffWiFi = lv_imgbtn_create(ui_PanelWiFi);
    lv_imgbtn_set_src(ui_OnOffWiFi, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_wifi_released_png, NULL);
    lv_imgbtn_set_src(ui_OnOffWiFi, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_wifi_released_png, NULL);
    lv_imgbtn_set_src(ui_OnOffWiFi, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_wifi_pressed_png, NULL);
    lv_imgbtn_set_src(ui_OnOffWiFi, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_wifi_pressed_png, NULL);
    lv_obj_set_width(ui_OnOffWiFi, 32);
    lv_obj_set_height(ui_OnOffWiFi, 32);
    lv_obj_set_x(ui_OnOffWiFi, 53);
    lv_obj_set_y(ui_OnOffWiFi, -9);
    lv_obj_add_flag(ui_OnOffWiFi, LV_OBJ_FLAG_CHECKABLE);     /// Flags

    ui_EnterPass = lv_btn_create(ui_PanelWiFi);
    lv_obj_set_width(ui_EnterPass, 35);
    lv_obj_set_height(ui_EnterPass, 35);
    lv_obj_set_x(ui_EnterPass, 133);
    lv_obj_set_y(ui_EnterPass, 15);
    lv_obj_set_align(ui_EnterPass, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_EnterPass, lv_color_hex(0x4A4C4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EnterPass, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPass = lv_label_create(ui_EnterPass);
    lv_obj_set_width(ui_LabelPass, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPass, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelPass, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPass, "确定");
    lv_obj_set_style_text_font(ui_LabelPass, &ui_font_AlimamaShuHeiTiFont16Bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWiFiState = lv_label_create(ui_PanelWiFi);
    lv_obj_set_width(ui_LabelWiFiState, 80);
    lv_obj_set_height(ui_LabelWiFiState, 20);
    lv_obj_set_x(ui_LabelWiFiState, 100);
    lv_obj_set_y(ui_LabelWiFiState, 0);
    lv_label_set_long_mode(ui_LabelWiFiState, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LabelWiFiState, "已连接");
    lv_obj_set_style_text_font(ui_LabelWiFiState, &ui_font_AlimamaShuHeiTiFont16Bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPass = lv_obj_create(ui_Set);
    lv_obj_set_width(ui_PanelPass, 310);
    lv_obj_set_height(ui_PanelPass, 227);
    lv_obj_set_x(ui_PanelPass, 0);
    lv_obj_set_y(ui_PanelPass, -1);
    lv_obj_set_align(ui_PanelPass, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelPass, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelPass, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelPass, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPass, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelPass, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelPass, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KeyboardPass = lv_keyboard_create(ui_PanelPass);
    lv_obj_set_width(ui_KeyboardPass, 300);
    lv_obj_set_height(ui_KeyboardPass, 120);
    lv_obj_set_x(ui_KeyboardPass, -1);
    lv_obj_set_y(ui_KeyboardPass, 10);
    lv_obj_set_align(ui_KeyboardPass, LV_ALIGN_BOTTOM_MID);

    ui_PanelWiFiPass = lv_obj_create(ui_PanelPass);
    lv_obj_set_width(ui_PanelWiFiPass, 213);
    lv_obj_set_height(ui_PanelWiFiPass, 82);
    lv_obj_set_x(ui_PanelWiFiPass, -4);
    lv_obj_set_y(ui_PanelWiFiPass, -66);
    lv_obj_set_align(ui_PanelWiFiPass, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelWiFiPass, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextAreaWiFiPass = lv_textarea_create(ui_PanelWiFiPass);
    lv_obj_set_width(ui_TextAreaWiFiPass, 192);
    lv_obj_set_height(ui_TextAreaWiFiPass, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_x(ui_TextAreaWiFiPass, 1);
    lv_obj_set_y(ui_TextAreaWiFiPass, 7);
    lv_obj_set_align(ui_TextAreaWiFiPass, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaWiFiPass, "Placeholder...");
    lv_textarea_set_one_line(ui_TextAreaWiFiPass, true);



    ui_LabelWiFiName = lv_label_create(ui_PanelWiFiPass);
    lv_obj_set_width(ui_LabelWiFiName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWiFiName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWiFiName, -7);
    lv_obj_set_y(ui_LabelWiFiName, -25);
    lv_obj_set_align(ui_LabelWiFiName, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabelWiFiName, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LabelWiFiName, "WiFiName");
    lv_obj_set_style_text_font(ui_LabelWiFiName, &ui_font_AlimamaShuHeiTiFont16Bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CancelEnterPass = lv_btn_create(ui_PanelWiFiPass);
    lv_obj_set_width(ui_CancelEnterPass, 20);
    lv_obj_set_height(ui_CancelEnterPass, 20);
    lv_obj_set_x(ui_CancelEnterPass, -9);
    lv_obj_set_y(ui_CancelEnterPass, -12);
    lv_obj_set_style_bg_color(ui_CancelEnterPass, lv_color_hex(0xECECEC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CancelEnterPass, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCancel = lv_label_create(ui_CancelEnterPass);
    lv_obj_set_width(ui_LabelCancel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCancel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelCancel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCancel, "X");
    lv_obj_set_style_text_color(ui_LabelCancel, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpinnerWiFi = lv_spinner_create(ui_Set, 1000, 90);
    lv_obj_set_width(ui_SpinnerWiFi, 80);
    lv_obj_set_height(ui_SpinnerWiFi, 80);
    lv_obj_set_align(ui_SpinnerWiFi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SpinnerWiFi, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_SpinnerWiFi, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_add_event_cb(ui_SetBackToMain, ui_event_SetBackToMain, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderLight, ui_event_SliderLight, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RollerWiFi, ui_event_RollerWiFi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffWiFi, ui_event_OnOffWiFi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_EnterPass, ui_event_EnterPass, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_KeyboardPass, ui_TextAreaWiFiPass);
    lv_obj_add_event_cb(ui_KeyboardPass, ui_event_KeyboardPass, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CancelEnterPass, ui_event_CancelEnterPass, LV_EVENT_ALL, NULL);

}
