// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Serial_screen_init(void)
{
    ui_Serial = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Serial, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_bg_color(ui_Serial, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Serial, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_SerialBackToMain = lv_imgbtn_create(ui_Serial);
    lv_imgbtn_set_src(ui_SerialBackToMain, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_back_released_png, NULL);
    lv_imgbtn_set_src(ui_SerialBackToMain, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_back_pressed_png, NULL);
    lv_obj_set_width(ui_SerialBackToMain, 32);
    lv_obj_set_height(ui_SerialBackToMain, 32);
    lv_obj_set_x(ui_SerialBackToMain, 2);
    lv_obj_set_y(ui_SerialBackToMain, 8);

    ui_TextAreaTX = lv_textarea_create(ui_Serial);
    lv_obj_set_width(ui_TextAreaTX, 210);
    lv_obj_set_height(ui_TextAreaTX, 99);
    lv_obj_set_x(ui_TextAreaTX, -18);
    lv_obj_set_y(ui_TextAreaTX, -58);
    lv_obj_set_align(ui_TextAreaTX, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaTX, "TX...");
    lv_obj_set_style_text_font(ui_TextAreaTX, &ui_font_AlimamaShuHeiTiFont16Bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TextAreaTX, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextAreaTX, lv_color_hex(0x008FFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextAreaTX, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_TextAreaRX = lv_textarea_create(ui_Serial);
    lv_obj_set_width(ui_TextAreaRX, 210);
    lv_obj_set_height(ui_TextAreaRX, 116);
    lv_obj_set_x(ui_TextAreaRX, -18);
    lv_obj_set_y(ui_TextAreaRX, 58);
    lv_obj_set_align(ui_TextAreaRX, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaRX, "RX...");
    lv_obj_set_style_text_font(ui_TextAreaRX, &ui_font_AlimamaShuHeiTiFont16Bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TextAreaRX, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextAreaRX, lv_color_hex(0x008FFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextAreaRX, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_SerialTX = lv_imgbtn_create(ui_Serial);
    lv_imgbtn_set_src(ui_SerialTX, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_serialsend_released_png, NULL);
    lv_imgbtn_set_src(ui_SerialTX, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_serialsend_pressed_png, NULL);
    lv_obj_set_width(ui_SerialTX, 48);
    lv_obj_set_height(ui_SerialTX, 48);
    lv_obj_set_x(ui_SerialTX, 121);
    lv_obj_set_y(ui_SerialTX, -53);
    lv_obj_set_align(ui_SerialTX, LV_ALIGN_CENTER);

    ui_SerialDelete = lv_imgbtn_create(ui_Serial);
    lv_imgbtn_set_src(ui_SerialDelete, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_serialdelete_released_png, NULL);
    lv_imgbtn_set_src(ui_SerialDelete, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_serialdelete_pressed_png, NULL);
    lv_obj_set_width(ui_SerialDelete, 48);
    lv_obj_set_height(ui_SerialDelete, 48);
    lv_obj_set_x(ui_SerialDelete, 121);
    lv_obj_set_y(ui_SerialDelete, 55);
    lv_obj_set_align(ui_SerialDelete, LV_ALIGN_CENTER);

    ui_KeyboardSerial = lv_keyboard_create(ui_Serial);
    lv_obj_set_width(ui_KeyboardSerial, 300);
    lv_obj_set_height(ui_KeyboardSerial, 120);
    lv_obj_set_align(ui_KeyboardSerial, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_KeyboardSerial, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_set_style_radius(ui_KeyboardSerial, 5, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_KeyboardSerial, lv_color_hex(0x00E4FF), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KeyboardSerial, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SerialBackToMain, ui_event_SerialBackToMain, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaTX, ui_event_TextAreaTX, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SerialTX, ui_event_SerialTX, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SerialDelete, ui_event_SerialDelete, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_KeyboardSerial, ui_TextAreaTX);

}
