// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Weather_screen_init(void)
{
    ui_Weather = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Weather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_bg_color(ui_Weather, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Weather, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_TabViewWeather = lv_tabview_create(ui_Weather, LV_DIR_RIGHT, 40);
    lv_obj_set_width(ui_TabViewWeather, 316);
    lv_obj_set_height(ui_TabViewWeather, 234);
    lv_obj_set_x(ui_TabViewWeather, 0);
    lv_obj_set_y(ui_TabViewWeather, -1);
    lv_obj_set_align(ui_TabViewWeather, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabViewWeather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TabViewWeather, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabViewWeather, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_TabViewWeather), &ui_font_AlimamaShuHeiTiFont16Bpp4,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabToday = lv_tabview_add_tab(ui_TabViewWeather, "实况天气");

    ui_ImageCode = lv_img_create(ui_TabToday);
    lv_img_set_src(ui_ImageCode, &ui_img_weather_code_png);
    lv_obj_set_width(ui_ImageCode, 48);
    lv_obj_set_height(ui_ImageCode, 48);
    lv_obj_set_x(ui_ImageCode, -105);
    lv_obj_set_y(ui_ImageCode, 10);
    lv_obj_set_align(ui_ImageCode, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageCode, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageCode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageTemp = lv_img_create(ui_TabToday);
    lv_img_set_src(ui_ImageTemp, &ui_img_weather_temp_png);
    lv_obj_set_width(ui_ImageTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageTemp, -105);
    lv_obj_set_y(ui_ImageTemp, 70);
    lv_obj_set_align(ui_ImageTemp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageTemp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageLocation = lv_img_create(ui_TabToday);
    lv_img_set_src(ui_ImageLocation, &ui_img_weather_location_png);
    lv_obj_set_width(ui_ImageLocation, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageLocation, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageLocation, -105);
    lv_obj_set_y(ui_ImageLocation, -50);
    lv_obj_set_align(ui_ImageLocation, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageLocation, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageLocation, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelCode = lv_label_create(ui_TabToday);
    lv_obj_set_width(ui_LabelCode, 180);
    lv_obj_set_height(ui_LabelCode, 20);
    lv_obj_set_x(ui_LabelCode, 30);
    lv_obj_set_y(ui_LabelCode, 10);
    lv_obj_set_align(ui_LabelCode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCode, "初始化中...");
    lv_obj_set_style_text_font(ui_LabelCode, &ui_font_AlimamaShuHeiTiFont16Bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTemp = lv_label_create(ui_TabToday);
    lv_obj_set_width(ui_LabelTemp, 180);
    lv_obj_set_height(ui_LabelTemp, 20);
    lv_obj_set_x(ui_LabelTemp, 30);
    lv_obj_set_y(ui_LabelTemp, 70);
    lv_obj_set_align(ui_LabelTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTemp, "初始化中...");
    lv_obj_set_style_text_font(ui_LabelTemp, &ui_font_AlimamaShuHeiTiFont16Bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLocation = lv_label_create(ui_TabToday);
    lv_obj_set_width(ui_LabelLocation, 180);
    lv_obj_set_height(ui_LabelLocation, 20);
    lv_obj_set_x(ui_LabelLocation, 30);
    lv_obj_set_y(ui_LabelLocation, -50);
    lv_obj_set_align(ui_LabelLocation, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLocation, "初始化中...");
    lv_obj_set_style_text_font(ui_LabelLocation, &ui_font_AlimamaShuHeiTiFont16Bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelUpdateTime = lv_label_create(ui_TabToday);
    lv_obj_set_width(ui_LabelUpdateTime, 180);
    lv_obj_set_height(ui_LabelUpdateTime, 20);
    lv_obj_set_align(ui_LabelUpdateTime, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_LabelUpdateTime, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LabelUpdateTime, "上次更新时间:初始化中...");
    lv_obj_set_style_text_font(ui_LabelUpdateTime, &ui_font_AlimamaShuHeiTiFont16Bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabFuture = lv_tabview_add_tab(ui_TabViewWeather, "预报天气");

    ui_RollerFuture = lv_roller_create(ui_TabFuture);
    lv_roller_set_options(ui_RollerFuture, "初始化中...\n", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_RollerFuture, 253);
    lv_obj_set_height(ui_RollerFuture, 175);
    lv_obj_set_x(ui_RollerFuture, -2);
    lv_obj_set_y(ui_RollerFuture, 12);
    lv_obj_set_align(ui_RollerFuture, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_RollerFuture, &ui_font_AlimamaShuHeiTiFont16Bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_RollerFuture, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RollerFuture, lv_color_hex(0xACACAC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerFuture, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RollerFuture, lv_color_hex(0x2B2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RollerFuture, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_RollerFuture, lv_color_hex(0x4F4F4F), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerFuture, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_LabelTomorrowCode = lv_label_create(ui_TabFuture);
    lv_obj_set_width(ui_LabelTomorrowCode, 180);
    lv_obj_set_height(ui_LabelTomorrowCode, 20);
    lv_obj_set_align(ui_LabelTomorrowCode, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_LabelTomorrowCode, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LabelTomorrowCode, "初始化中...");
    lv_obj_set_style_text_font(ui_LabelTomorrowCode, &ui_font_AlimamaShuHeiTiFont16Bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherBackToMain = lv_imgbtn_create(ui_Weather);
    lv_imgbtn_set_src(ui_WeatherBackToMain, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_back_released_png, NULL);
    lv_imgbtn_set_src(ui_WeatherBackToMain, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_back_pressed_png, NULL);
    lv_obj_set_width(ui_WeatherBackToMain, 32);
    lv_obj_set_height(ui_WeatherBackToMain, 32);
    lv_obj_set_x(ui_WeatherBackToMain, 2);
    lv_obj_set_y(ui_WeatherBackToMain, 8);

    ui_WeatherUpdate = lv_imgbtn_create(ui_Weather);
    lv_imgbtn_set_src(ui_WeatherUpdate, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_weatherupdate_released_png, NULL);
    lv_imgbtn_set_src(ui_WeatherUpdate, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_weatherupdate_pressed_png, NULL);
    lv_obj_set_width(ui_WeatherUpdate, 32);
    lv_obj_set_height(ui_WeatherUpdate, 32);
    lv_obj_set_x(ui_WeatherUpdate, 240);
    lv_obj_set_y(ui_WeatherUpdate, 8);

    lv_obj_add_event_cb(ui_WeatherBackToMain, ui_event_WeatherBackToMain, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WeatherUpdate, ui_event_WeatherUpdate, LV_EVENT_ALL, NULL);

}
